name: Download Cache

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache
        id: restore
        uses: actions/cache/restore@v4
        with:
          path: cache
          key: prefix-state-e7e2b600b801d8cca9e210db273a618368674fe436c065f4b321e3bd4c38b25c-v3
          fail-on-cache-miss: true

      - name: Show restored files
        run: |
          echo "Cache hit: ${{ steps.restore.outputs.cache-hit }}"
          ls -lahR cache

      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: restored-cache
          path: cache
